_target_: pangaea.datasets.toy_flair.ToyFLAIR
dataset_name: ToyFLAIR
root_path: /content/pangaea-bench/toyFLAIR
download_url: False 
auto_download: False

img_size: 512
multi_temporal: False
multi_modal: False

# classes
ignore_index: 18
num_classes: 19
classes:
  - building
  - pervious surface
  - impervious surface
  - bare soil
  - water
  - coniferous
  - deciduous
  - brushwood
  - vineyard
  - herbaceous
  - agricultural
  - plowed
  - swimming pool
  - snow 
  - clear cut
  - mixed
  - ligneous
  - greenhouse
  - other
distribution:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

bands:
  optical:
    - B4
    - B3
    - B2
data_mean:
  optical:
    - 124.3
    - 94.2
    - 98.
data_std:
  optical:
    - 51.
    - 50.
    - 47.1
data_min:
  optical: [0.0000, 0.0000, 0.0000]
data_max:
  optical: [1.0000, 1.0000, 1.0000]
